title: Amanda Escalona
author:
  name: Amanda Escalona 
  email: amandaescalona30@gmail.com
tag: creative writer
description: > # this means to ignore newlines until "show_excerpts:"
 🦉🤓Nerd freelancer: Redactora de contenido, copy writer, community manager, escritora por las noches 🦇 y lectora ávida ⚡. ¡Lista para generar contenido persuasivo que aumente tus ventas!🖤



bio: >
 "¿Ratón de biblioteca? Es posible, tanto así que he vivido gran parte de mi vida con un libro debajo del brazo. Entonces quise hacer de la literatura mi vida y estudié letras en la Universidad Católica Andrés Bello. Luego de eso me encontré, de un golpe inesperado, con el marketing, entonces uní mi amor por escribir, con el amor por la tecnología y la comunicación, y me convertí en mi yo de ahora: Redactora de contenido, community manager, escritora por las noches y lectora ávida. He escrito de todo un poco, desde tecnología, hasta medicina y psicología infantil. Asimismo, me gusta investigar, estudiar el tema que estoy trabajando y escribir con la mayor fidelidad posible, es decir, siempre hago un estudio de vocabulario oterminología antes de realizar el trabajo."

show_excerpts: false # set to true to show excerpts on the homepage


defaults:
  - scope:
      path: "assets/images"
      type: 'image'
    values:
      image: true

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this\


minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:   
    - { platform: instagram,      user_url: "https://www.instagram.com/amanda_nadhia/" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
    - { platform: telegram,       user_url: "https://t.me/jekyll" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

# Enable safe mode
safe: true

# Whitelist plugins under safe mode.
# Note that `some-other-jekyll-plugin` is not listed here. Therefore,
# it will not be loaded under safe mode.
whitelist:
 - jekyll-admin